1)Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [10]:
import numpy as np


In [11]:
arr = np.arange(2,50,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [31]:
a=int(input("Size of array in a:"))
b=int(input("Size of array in b:"))
my_arraya = numpy.empty(a)
my_arrayb = numpy.empty(b)
for i in range(len(my_arraya)):
    x=float(input("Element of a:"))
    my_arraya[i]=x
  #  print(numpy.floor(my_arraya))
    
for j in range(len(my_arrayb)):
    y=float(input("Element of b:"))
    my_arrayb[j]=y
    
print(numpy.floor(my_arraya))
print(numpy.floor(my_arrayb))

arr = np.concatenate([my_arraya, my_arrayb])

print(np.sort(arr))

Size of array in a:3
Size of array in b:3
Element of a:1
Element of a:3
Element of a:5
Element of b:2
Element of b:4
Element of b:6
[1. 3. 5.]
[2. 4. 6.]
[1. 2. 3. 4. 5. 6.]


In [32]:
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
 

# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)


No. of dimensions:  2
Size of array:  6


In [35]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape
print(a)
a2 = a[np.newaxis, :]
a2.shape
print(a2)
b = np.expand_dims(a, axis=0)
b.shape
print(b)

[1 2 3 4 5 6]
[[1 2 3 4 5 6]]
[[1 2 3 4 5 6]]


In [36]:
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

a = np.array([1,2,3])
b = np.array([4,5,6])

print('Vertical Append:', np.vstack((a, b)))

Horizontal Append: [1 2 3 4 5 6]
Vertical Append: [[1 2 3]
 [4 5 6]]


In [ ]:
numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)